/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Utils;

import com.github.lgooddatepicker.components.DatePickerSettings;
import com.github.lgooddatepicker.components.DateTimePicker;
import com.github.lgooddatepicker.components.TimePickerSettings;
import com.github.lgooddatepicker.optionalusertools.PickerUtilities;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.time.Instant;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import javax.swing.JButton;
import javax.swing.JFrame;
import static javax.swing.JFrame.EXIT_ON_CLOSE;
import javax.swing.JLabel;
import javax.swing.UIManager;
import org.apache.logging.log4j.LogManager;

/**
 *
 * @author Stepan
 */
public class TDateRange extends javax.swing.JPanel {

    @Override
    public void setEnabled(boolean enabled) {
        super.setEnabled(enabled); //To change body of generated methods, choose Tools | Templates.
        if (refreshBt != null) {
            refreshBt.setEnabled(enabled);
        }
        dtFrom.setEnabled(enabled);
        dtTo.setEnabled(enabled);
        jlFrom.setEnabled(enabled);
        jlTo.setEnabled(enabled);
    }

    public void enableFrom(boolean enabled) {
        dtFrom.setEnabled(enabled);
        jlFrom.setEnabled(enabled);
    }

    public void enableTo(boolean enabled) {
        dtTo.setEnabled(enabled);
        jlTo.setEnabled(enabled);
    }

    public static interface IRefresh {

        UTCTimeRange Refresh();
    };

    private IRefresh refreshCB = null;

    public IRefresh getRefreshCB() {
        return refreshCB;
    }

    public void setRefreshCB(IRefresh refreshCB) {
        this.refreshCB = refreshCB;
        refreshBt = new JButton("refresh");
        add(refreshBt);

        refreshBt.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                IRefresh refreshCB1 = getRefreshCB();
                if (refreshCB1 != null) {
                    setTimeRange(refreshCB1.Refresh());
                }
            }
        });

    }

    private JButton refreshBt;

    /**
     * Creates new form TDateRange
     */
    JLabel jlFrom;
    JLabel jlTo;

    public TDateRange() {
        this(true);
    }

    public TDateRange(boolean showSeconds) {
        initComponents();
        initDates(showSeconds);

    }

    private void initDates(boolean showSeconds) {
        String dateFormat = (showSeconds) ? "HH:mm:ss" : "HH:mm";
        setLayout(new FlowLayout());

        jlFrom = new JLabel("From");
        add(jlFrom);
        dtFrom = newPicker(dateFormat);
        add(dtFrom);
        jlTo = new JLabel("To");
        add(jlTo);
        dtTo = newPicker(dateFormat);
        add(dtTo);

        dtFrom.getTimePicker().getSettings().setDisplayToggleTimeMenuButton(true);
        dtTo.getTimePicker().getSettings().setDisplayToggleTimeMenuButton(true);

    }

    private DateTimePicker dtFrom;
    private DateTimePicker dtTo;

    private DateTimePicker newPicker() {
        return newPicker("HH:mm:ss");
    }

    private DateTimePicker newPicker(String dateFormat) {
        DateTimePicker dateTimePicker1 = new DateTimePicker();
//        dateTimePicker1.datePicker.setDate(LocalDate.now());
//        dateTimePicker1.timePicker.setTimeToNow();
        TimePickerSettings timeSettings = dateTimePicker1.getTimePicker().getSettings();
        timeSettings.setFormatForDisplayTime(PickerUtilities.createFormatterFromPatternString(
                dateFormat, timeSettings.getLocale()));
        timeSettings.setFormatForMenuTimes(PickerUtilities.createFormatterFromPatternString(
                dateFormat, timeSettings.getLocale()));
        return dateTimePicker1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 463, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 154, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String[] args) {
        // Trying to set Nimbus look and feel
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            logger.log(org.apache.logging.log4j.Level.FATAL, "Failed to apply Nimbus look and feel", ex);

        }
        TDateRange tDateRange = new TDateRange();
        JFrame jf = new JFrame();
        jf.setLayout(new FlowLayout());
        jf.setSize(new Dimension(640, 480));
        jf.add(tDateRange);
        jf.setVisible(true);
        jf.setDefaultCloseOperation(EXIT_ON_CLOSE);
    }
    private static final org.apache.logging.log4j.Logger logger = LogManager.getLogger();

    public UTCTimeRange getTimeRange() {
        if (dtFrom.isEnabled() && dtTo.isEnabled()) {
            UTCTimeRange range = new UTCTimeRange();

            range.setStart(getUtcTime(dtFrom.getDateTimePermissive(), zoneId, 0));
            range.setEnd(getUtcTime(dtTo.getDateTimePermissive(), zoneId, 1));
//        inquirer.inquirer.logger.info("setTimeRange " + range.get(0) + " to " + range.get(1));
            return range;
        }
        return null;
    }

    public UTCTimeRange getTimeRangeAlways() {
        UTCTimeRange range = new UTCTimeRange();

        if (dtFrom.isEnabled()) {
            range.setStart(getUtcTime(dtFrom.getDateTimePermissive(), zoneId, 0));
        } else {
            range.setStart((long) 0);
        }
        if (dtTo.isEnabled()) {
            range.setEnd(getUtcTime(dtTo.getDateTimePermissive(), zoneId, 1));
        } else {
            range.setEnd((long) 0);
        }
//        inquirer.inquirer.logger.info("setTimeRange " + range.get(0) + " to " + range.get(1));
        return range;
    }

    public static final ZoneId zoneId = ZoneId.systemDefault();

    public static long getUTCTime(DateTimePicker dtp, int adjustment) {
        return getUtcTime(dtp.getDateTimePermissive(), zoneId, adjustment);
    }

    public static void setTimeRange(DateTimePicker dtp, long time) {
        ZonedDateTime zoneDateTime = (Instant.ofEpochMilli(time)).atZone(zoneId);

        dtp.setDateTimePermissive(zoneDateTime.toLocalDateTime());
        DatePickerSettings dateSettings = dtp.getDatePicker().getSettings();
//        dateSettings.setDateRangeLimits(zoneDateTime.toLocalDate(), zoneDateTime.toLocalDate());

//            long toEpochDay = dtFrom.getDatePicker().getDate().atTime(LocalTime.MIN)
//            inquirer.inquirer.logger.info("getTimeRange toEpochDay " + toEpochDay);
//            long toNanoOfDay = dtFrom.getTimePicker().getTime().toNanoOfDay();
//            inquirer.inquirer.logger.info("getTimeRange toNanoOfDay " + toEpochDay +"total: "+toEpochDay*1000000+toNanoOfDay);
//            instantFrom = dtLocalFrom.toInstant(ZoneOffset.UTC);
//            inquirer.inquirer.logger.info("instant: "+instantFrom+" getTimeRange " + instantFrom.getEpochSecond() + " to " + instantFrom.getNano());
    }

    public void setTimeRange(UTCTimeRange timeRange) {
        dtFrom.setEnabled(!(timeRange == null));
        dtTo.setEnabled(!(timeRange == null));

        if (timeRange == null) {
            dtFrom.getDatePicker().clear();
            dtFrom.getTimePicker().clear();
            dtTo.getDatePicker().clear();
            dtTo.getTimePicker().clear();
        } else {
            logger.debug("setTimeRange " + timeRange.getStart() + " to " + timeRange.getEnd());
            setTimeRange(dtFrom, timeRange.getStart());
            setTimeRange(dtTo, timeRange.getEnd());

        }
    }

    static public long getUtcTime(LocalDateTime dateTime, int adjustment) {
        return getUtcTime(dateTime, zoneId, adjustment);
    }

    static private Long getUtcTime(LocalDateTime dateTime, ZoneId _zoneID, int adjustment) {
        logger.debug("getUtcTime " + dateTime);
        return (dateTime.toInstant(_zoneID.getRules().getOffset(dateTime)).getEpochSecond() + adjustment) * 1000;

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
